### PR TITLE
Enhacement | base-network: Update versions constraint + Update module version 

### PR DESCRIPTION
**Pull request by rodriguez-matias**
## What?
* Update and test **Ref Architecture** layers  with tf latest versions, Leverage CLI latest version and SSO feature enabled.

## How?
* Update tf version constrains `~> v1.2.7`
* Update tf aws provider constrains  `~> v4.10`
* Update module version to the latest available

## Environment Versions
+ Leverage CLI : v1.8
+ Terraform:  v1.2.7
+ provider registry.terraform.io/hashicorp/aws v4.45.0

## Layers
**apps-devstg**/us-east-1/base-network
**apps-prod**/us-east-1/base-network
**network**/us-east-1/base-network
**shared**/us-east-1/base-network
**shared**/us-east-2/base-network

## Why?
Keeping Leverage Reference Architecture up to date.

## References
GitHub issue https://github.com/binbashar/le-tf-infra-aws/issues/370

### CODE REVIEW

**Comment by rodriguez-matias** [comment]
### terraform commands

### $ leverage terraform init

```
[08:17:58.789] INFO     Checking environment name definition in account.tfvars...
[08:17:58.797] INFO     ✔ OK
[08:17:58.811] INFO     Checking backend key...
[08:17:58.813] INFO     Found: 'apps-devstg/network/terraform.tfstate'
[08:17:58.816] INFO     ✔ OK
[08:17:58.820] INFO     Checking backend.tfvars:
[08:17:58.823] INFO     Checking if profile starts with bb-apps-devstg...
[08:17:58.825] INFO     ✔ OK
[08:17:58.827] INFO     Checking if bucket starts with bb-apps-devstg...
[08:17:58.829] INFO     ✔ OK
[08:17:58.832] INFO     Checking if dynamodb table starts with bb-apps-devstg...
[08:17:58.835] INFO     ✔ OK
[11:18:02]    INFO      Attempting to get temporary credentials for apps-devstg account.
[11:18:13]    INFO      Credentials for apps-devstg account written successfully.
[11:18:13]    INFO      Attempting to get temporary credentials for network account.
[11:18:22]    INFO      Credentials for network account written successfully.
[11:18:22]    INFO      Attempting to get temporary credentials for shared account.
[11:18:31]    INFO      Credentials for shared account written successfully.

Initializing modules...
Initializing the backend...
Initializing provider plugins...

- terraform.io/builtin/terraform is built in to Terraform
- Reusing previous version of hashicorp/aws from the dependency lock file
- Installing hashicorp/aws v4.44.0...
- Installed hashicorp/aws v4.44.0 (signed by HashiCorp)

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by rodriguez-matias** [comment]
### $ leverage terraform apply

```
[11:23:07]    INFO      Attempting to get temporary credentials for apps-devstg account.
[11:23:09]    INFO      Using already configured temporary credentials.
[11:23:09]    INFO      Attempting to get temporary credentials for network account.
[11:23:11]    INFO      Using already configured temporary credentials.
[11:23:11]    INFO      Attempting to get temporary credentials for shared account.
[11:23:13]    INFO      Using already configured temporary credentials.
Acquiring state lock. This may take a few moments...
data.terraform_remote_state.shared-vpcs["shared-base"]: Reading...
.
.
.
module.vpc_peering_apps_devstg_to_eks_clusters["apps-devstg-k8s-eks-demoapps"].aws_route.peer_routes[0]: Refreshing state... [id=r-rtb-XXXXXXXXX]
module.vpc_endpoints["s3"].aws_vpc_endpoint.this["endpoint"]: Refreshing state... [id=vpce-07427fafe5ccf2f1f]
module.vpc_endpoints["dynamodb"].aws_vpc_endpoint.this["endpoint"]: Refreshing state... [id=vpce-XXXXXXXX]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # module.vpc_flow_logs.aws_s3_bucket_policy.default will be destroyed
  # (because aws_s3_bucket_policy.default is not in configuration)
  - resource "aws_s3_bucket_policy" "default" {
      - bucket = "bb-apps-devstg-vpc-flowlogs" -> null

      - id     = "bb-apps-devstg-vpc-flowlogs" -> null
      - policy = jsonencode(
            {
              - Id        = "TerraformStateBucketPolicies"
              - Statement = [
                  - {
                      - Action    = "s3:*"
                      - Condition = {
                          - Bool = {
                              - "aws:SecureTransport" = "false"
                            }
                        }
                      - Effect    = "Deny"
                      - Principal = "*"
                      - Resource  = "arn:aws:s3:::bb-apps-devstg-vpc-flowlogs/*"
                      - Sid       = "EnforceSSlRequestsOnly"
                    },
                  - {
                      - Action    = "s3:PutObject"
                      - Condition = {
                          - StringEquals = {
                              - "s3:x-amz-acl" = "bucket-owner-full-control"
                            }
                        }
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "delivery.logs.amazonaws.com"
                        }
                      - Resource  = "arn:aws:s3:::bb-apps-devstg-vpc-flowlogs/*"
                      - Sid       = "AllowVpcFlowLogsDeliveryService"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
    }



 # module.vpc_flow_logs.aws_s3_bucket_policy.this[0] will be created
  + resource "aws_s3_bucket_policy" "this" {
      + bucket = "bb-apps-devstg-vpc-flowlogs"
      + id     = (known after apply)
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "s3:*"
                      + Condition = {
                          + Bool = {
                              + "aws:SecureTransport" = [
                                  + "false",

                                ]
                            }
                        }
                      + Effect    = "Deny"
                      + Principal = {
                          + AWS = "*"
                        }
                      + Resource  = "arn:aws:s3:::bb-apps-devstg-vpc-flowlogs/*"
                      + Sid       = "EnforceSSlRequestsOnly"
                    },
                  + {
                      + Action    = "s3:PutObject"
                      + Condition = {
                          + "ForAnyValue:StringEquals" = {
                              + "s3:x-amz-acl" = [
                                  + "bucket-owner-full-control",
                                ]
                            }
                        }
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "delivery.logs.amazonaws.com"
                        }
                      + Resource  = "arn:aws:s3:::bb-apps-devstg-vpc-flowlogs/*"
                      + Sid       = "AllowVpcFlowLogsDeliveryService"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 1 to destroy.
╷
│ Warning: Argument is deprecated
│
│   with module.vpc_flow_logs.aws_s3_bucket.this,
│   on .terraform/modules/vpc_flow_logs/main.tf line 14, in resource "aws_s3_bucket" "this":
│   14: resource "aws_s3_bucket" "this" {
│
│ Use the aws_s3_bucket_server_side_encryption_configuration resource instead
│
│ (and 7 more similar warnings elsewhere)
╵


Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.vpc_flow_logs.aws_s3_bucket_policy.default: Destroying... [id=bb-apps-devstg-vpc-flowlogs]
module.vpc_flow_logs.aws_s3_bucket_policy.this[0]: Creating...
module.vpc_flow_logs.aws_s3_bucket_policy.this[0]: Creation complete after 1s [id=bb-apps-devstg-vpc-flowlogs]

module.vpc_flow_logs.aws_s3_bucket_policy.default: Destruction complete after 1s
Releasing state lock. This may take a few moments...

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

Outputs:

availability_zones = [
  "us-east-1a",
  "us-east-1b",
  "us-east-1c",
]
nat_gateway_ids = []
private_route_table_ids = [
  "rtb-XXXXXX",
]
private_subnets = [
  "subnet-XXXXXX",
  "subnet-XXXXXXX",
  "subnet-XXXXXXX",
]
private_subnets_cidr = [
  "X.X.X.X/21",
]
public_route_table_ids = [
  "rtb-09XXXXXXX6a",
]
public_subnets = [
  "subnet-XXXXXX",
  "subnet-XXXXXXX",
  "subnet-XXXXXX",
]
public_subnets_cidr = [
  "X.X.X.0/21",
]
vpc_cidr_block = "X.X.X.0/20"
vpc_id = "vpc-072XXXXXXXXXXe95"
vpc_name = "bb-apps-devstg-vpc"
```

**Comment by rodriguez-matias** [comment]
### $ leverage --version

```
leverage, version 1.8.0
```

### $ leverage tf version

```
Terraform v1.2.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.45.0
```

**Review by exequielrafaela — CHANGES_REQUESTED** [review]
@rodriguez-matias we'll need to fix the conflicts before merging. After conflicts are resolved we could move forward with the review and merge. Thanks!

**Comment by rodriguez-matias** [comment]
@exequielrafaela  Ok resolved!

**Review by exequielrafaela — APPROVED** [review]

**Pull request merged**
