### PR TITLE
Feature/ shared/backups update tf providers versions

### PR DESCRIPTION
**Pull request by rodriguez-matias**
## What?
Update and Test Ref Architecture Certs layers (devstg and prd) with tf providers latest versions, Leverage CLI latest version and SSO feature enabled.

## Environment Versions
Leverage CLI : v1.7.0
Terraform : v1.1.9
Provider hashicorp/aws: v4.17.1

## Layers
**shared**/us-east-1/backups/

## How?
Update parameters in `config.tf`
Declare missing variables in `variables.tf` to solve warnings messages running tf apply:
"sso_role" , "sso_start_url" , "sso_enabled" , "sso_region" , "accounts" , "region_primary" , "enable_tgw" , "vault_token" , "vault_address"

## Why?
Keeping Leverage Reference Architecture up to date.

## References
GitHub issue https://github.com/binbashar/le-tf-infra-aws/issues/370

### CODE REVIEW

**Comment by rodriguez-matias** [comment]
I didn't find any breaking changes reported by official terraform documentation regarding aws_backup resources comparing tf-aws `v3.x` vs `v4.x`
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade
https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md

**Comment by rodriguez-matias** [comment]
### $ leverage tf init

```yaml
[19:21:51.700] INFO     Checking environment name definition in account.tfvars...
[19:21:51.708] INFO     ✔ OK
[19:21:51.713] INFO     Checking if backend key matches 'shared/backups/terraform.tfstate'...
[19:21:51.715] INFO     ✔ OK
[19:21:51.719] INFO     Checking backend.tfvars:
[19:21:51.721] INFO     Checking if profile starts with bb-shared...
[19:21:51.723] INFO     ✔ OK
[19:21:51.725] INFO     Checking if bucket starts with bb-shared...
[19:21:51.726] INFO     ✔ OK
[19:21:51.728] INFO     Checking if dynamodb table starts with bb-shared...
[19:21:51.729] INFO     ✔ OK
[22:21:53]    INFO Attempting to get temporary credentials for shared account.
[22:22:03]    INFO Credentials for shared account written successfully.
Initializing modules...
Downloading git::https://github.com/binbashar/terraform-aws-backup.git?ref=0.11.6 for daily_backups_tagged_resources...
- daily_backups_tagged_resources in .terraform/modules/daily_backups_tagged_resources

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/aws versions matching ">= 3.20.0, ~> 4.10"...
- Installing hashicorp/aws v4.17.1...
- Installed hashicorp/aws v4.17.1 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by rodriguez-matias** [comment]
### $ leverage tf apply

```yaml
[22:26:59]    INFO Attempting to get temporary credentials for shared account.
[22:27:01]    INFO Using already configured temporary credentials.
Acquiring state lock. This may take a few moments...
module.daily_backups_tagged_resources.aws_iam_role.ab_role[0]: Refreshing state... [id=aws-backup-plan-daily-backups-role]
module.daily_backups_tagged_resources.aws_iam_policy.ab_tag_policy[0]: Refreshing state... [id=arn:aws:iam::76********58:policy/terraform-20210211*********0000001]
module.daily_backups_tagged_resources.aws_backup_vault_notifications.backup_events[0]: Refreshing state... [id=bb-shared-default]
module.daily_backups_tagged_resources.aws_backup_vault.ab_vault[0]: Refreshing state... [id=bb-shared-default]
module.daily_backups_tagged_resources.aws_sns_topic_policy.backup_events[0]: Refreshing state... [id=arn:aws:sns:us-east-1:76********58:sns-topic-slack-notify-monitoring-sec]
module.daily_backups_tagged_resources.aws_backup_plan.ab_plan[0]: Refreshing state... [id=69ef7f93-54d0-4*******1ffee0918f]
module.daily_backups_tagged_resources.aws_iam_role_policy_attachment.ab_policy_attach[0]: Refreshing state... [id=aws-backup-plan-daily-backups-role-20210211********88700000002]
module.daily_backups_tagged_resources.aws_iam_role_policy_attachment.ab_tag_policy_attach[0]: Refreshing state... [id=aws-backup-plan-daily-backups-role-2021021*******7200000004]
module.daily_backups_tagged_resources.aws_iam_role_policy_attachment.ab_restores_policy_attach[0]: Refreshing state... [id=aws-backup-plan-daily-backups-role-2021021113521********00003]
module.daily_backups_tagged_resources.aws_backup_selection.ab_selection[0]: Refreshing state... [id=172260a4-5d2a*******631-52d06b9c5313]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
Releasing state lock. This may take a few moments...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```

**Comment by rodriguez-matias** [comment]
### $ leverage tf destroy

```yaml
[22:27:48]    INFO Attempting to get temporary credentials for shared account.
[22:27:50]    INFO Using already configured temporary credentials.
Acquiring state lock. This may take a few moments...
module.daily_backups_tagged_resources.aws_iam_policy.ab_tag_policy[0]: Refreshing state... [id=arn:aws:iam::76********58:policy/terraform-20210211******7000000001]
module.daily_backups_tagged_resources.aws_iam_role.ab_role[0]: Refreshing state... [id=aws-backup-plan-daily-backups-role]
module.daily_backups_tagged_resources.aws_backup_vault.ab_vault[0]: Refreshing state... [id=bb-shared-default]
module.daily_backups_tagged_resources.aws_backup_vault_notifications.backup_events[0]: Refreshing state... [id=bb-shared-default]
module.daily_backups_tagged_resources.aws_sns_topic_policy.backup_events[0]: Refreshing state... [id=arn:aws:sns:us-east-1:76********58:sns-topic-slack-notify-monitoring-sec]
module.daily_backups_tagged_resources.aws_backup_plan.ab_plan[0]: Refreshing state... [id=69ef7f93-******a-bb2f-851ffee0918f]
module.daily_backups_tagged_resources.aws_iam_role_policy_attachment.ab_tag_policy_attach[0]: Refreshing state... [id=aws-backup-plan-daily-backups-role-202102111******00000004]
module.daily_backups_tagged_resources.aws_iam_role_policy_attachment.ab_restores_policy_attach[0]: Refreshing state... [id=aws-backup-plan-daily-backups-role-202102******0000003]
module.daily_backups_tagged_resources.aws_iam_role_policy_attachment.ab_policy_attach[0]: Refreshing state... [id=aws-backup-plan-daily-backups-role-202102111******700000002]
module.daily_backups_tagged_resources.aws_backup_selection.ab_selection[0]: Refreshing state... [id=172260a4-5d2a-4******-52d06b9c5313]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # module.daily_backups_tagged_resources.aws_backup_plan.ab_plan[0] will be destroyed
  - resource "aws_backup_plan" "ab_plan" {
      - arn      = "arn:aws:backup:us-east-1:76********58:backup-plan:69ef7f93-54d0-******1ffee0918f" -> null
      - id       = "69ef7f9******d0a-bb2f-85******ee0918f" -> null
      - name     = "daily-backups" -> null
      - tags     = {
          - "Environment" = "shared"
          - "Terraform"   = "true"
        } -> null
      - tags_all = {
          - "Environment" = "shared"
          - "Terraform"   = "true"
        } -> null
      - version  = "ZjQyNDZkMmMtN2******0MmItYzhkMmUzNDY1YWJj" -> null

      - rule {
          - completion_window        = 360 -> null
          - enable_continuous_backup = false -> null
          - recovery_point_tags      = {
              - "Backup" = "True"
            } -> null
          - rule_name                = "daily-runs" -> null
          - schedule                 = "cron(0 20 * * ? *)" -> null
          - start_window             = 120 -> null
          - target_vault_name        = "bb-shared-default" -> null

          - lifecycle {
              - cold_storage_after = 0 -> null
              - delete_after       = 7 -> null
            }
        }
    }

  # module.daily_backups_tagged_resources.aws_backup_selection.ab_selection[0] will be destroyed
  - resource "aws_backup_selection" "ab_selection" {
      - iam_role_arn  = "arn:aws:iam::76********58:role/aws-backup-plan-daily-backups-role" -> null
      - id            = "17226******631-52d06b9c5313" -> null
      - name          = "tagged-resources" -> null
      - not_resources = [] -> null
      - plan_id       = "69ef7f9******-851ffee0918f" -> null
      - resources     = [] -> null

      - condition {
        }

      - selection_tag {
          - key   = "Backup" -> null
          - type  = "STRINGEQUALS" -> null
          - value = "True" -> null
        }
    }

  # module.daily_backups_tagged_resources.aws_backup_vault.ab_vault[0] will be destroyed
  - resource "aws_backup_vault" "ab_vault" {
      - arn             = "arn:aws:backup:us-east-1:76********58:backup-vault:bb-shared-default" -> null
      - id              = "bb-shared-default" -> null
      - kms_key_arn     = "arn:aws:kms:us-east-1:76********58:key/b0146712-9dfc-4******95bc5a2" -> null
      - name            = "bb-shared-default" -> null
      - recovery_points = 14 -> null
      - tags            = {
          - "Environment" = "shared"
          - "Terraform"   = "true"
        } -> null
      - tags_all        = {
          - "Environment" = "shared"
          - "Terraform"   = "true"
        } -> null
    }

  # module.daily_backups_tagged_resources.aws_backup_vault_notifications.backup_events[0] will be destroyed
  - resource "aws_backup_vault_notifications" "backup_events" {
      - backup_vault_arn    = "arn:aws:backup:us-east-1:76********58:backup-vault:bb-shared-default" -> null
      - backup_vault_events = [
          - "BACKUP_JOB_FAILED",
          - "BACKUP_JOB_STARTED",
          - "BACKUP_JOB_SUCCESSFUL",
        ] -> null
      - backup_vault_name   = "bb-shared-default" -> null
      - id                  = "bb-shared-default" -> null
      - sns_topic_arn       = "arn:aws:sns:us-east-1:76********58:sns-topic-slack-notify-monitoring-sec" -> null
    }

  # module.daily_backups_tagged_resources.aws_iam_policy.ab_tag_policy[0] will be destroyed
  - resource "aws_iam_policy" "ab_tag_policy" {
      - arn         = "arn:aws:iam::76********58:policy/terraform-2021021******000000001" -> null
      - description = "AWS Backup Tag policy" -> null
      - id          = "arn:aws:iam::76********58:policy/terraform-2021021113******000000001" -> null
      - name        = "terraform-202102******00001" -> null
      - path        = "/" -> null
      - policy      = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = [
                          - "backup:TagResource",
                          - "backup:ListTags",
                          - "backup:UntagResource",
                          - "tag:GetResources",
                        ]
                      - Effect   = "Allow"
                      - Resource = "*"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
      - policy_id   = "ANPA3******34K3A" -> null
      - tags        = {} -> null
      - tags_all    = {} -> null
    }

  # module.daily_backups_tagged_resources.aws_iam_role.ab_role[0] will be destroyed
  - resource "aws_iam_role" "ab_role" {
      - arn                   = "arn:aws:iam::76********58:role/aws-backup-plan-daily-backups-role" -> null
      - assume_role_policy    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "sts:AssumeRole"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "backup.amazonaws.com"
                        }
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
      - create_date           = "******" -> null
      - force_detach_policies = false -> null
      - id                    = "aws-backup-plan-daily-backups-role" -> null
      - managed_policy_arns   = [
          - "arn:aws:iam::76********58:policy/terraform-202102111352******000001",
          - "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup",
          - "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores",
        ] -> null
      - max_session_duration  = 3600 -> null
      - name                  = "aws-backup-plan-daily-backups-role" -> null
      - path                  = "/" -> null
      - tags                  = {
          - "Environment" = "shared"
          - "Terraform"   = "true"
        } -> null
      - tags_all              = {
          - "Environment" = "shared"
          - "Terraform"   = "true"
        } -> null
      - unique_id             = "AROA******RBDAB" -> null

      - inline_policy {}
    }

  # module.daily_backups_tagged_resources.aws_iam_role_policy_attachment.ab_policy_attach[0] will be destroyed
  - resource "aws_iam_role_policy_attachment" "ab_policy_attach" {
      - id         = "aws-backup-plan-daily-backups-role-202102******00000002" -> null
      - policy_arn = "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup" -> null
      - role       = "aws-backup-plan-daily-backups-role" -> null
    }

  # module.daily_backups_tagged_resources.aws_iam_role_policy_attachment.ab_restores_policy_attach[0] will be destroyed
  - resource "aws_iam_role_policy_attachment" "ab_restores_policy_attach" {
      - id         = "aws-backup-plan-daily-backups-role-2021021******000003" -> null
      - policy_arn = "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores" -> null
      - role       = "aws-backup-plan-daily-backups-role" -> null
    }

  # module.daily_backups_tagged_resources.aws_iam_role_policy_attachment.ab_tag_policy_attach[0] will be destroyed
  - resource "aws_iam_role_policy_attachment" "ab_tag_policy_attach" {
      - id         = "aws-backup-plan-daily-backups-role-2021021******000004" -> null
      - policy_arn = "arn:aws:iam::76********58:policy/terraform-20210211******00000001" -> null
      - role       = "aws-backup-plan-daily-backups-role" -> null
    }

  # module.daily_backups_tagged_resources.aws_sns_topic_policy.backup_events[0] will be destroyed
  - resource "aws_sns_topic_policy" "backup_events" {
      - arn    = "arn:aws:sns:us-east-1:76********58:sns-topic-slack-notify-monitoring-sec" -> null
      - id     = "arn:aws:sns:us-east-1:76********58:sns-topic-slack-notify-monitoring-sec" -> null
      - owner  = "76********58" -> null
      - policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "SNS:Publish"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "backup.amazonaws.com"
                        }
                      - Resource  = "arn:aws:sns:us-east-1:76********58:sns-topic-slack-notify-monitoring-sec"
                      - Sid       = "BackupPublishEvents"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
    }

Plan: 0 to add, 0 to change, 10 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: NO

Destroy cancelled.
Releasing state lock. This may take a few moments...
```

**Review by exequielrafaela — APPROVED** [review]
@rodriguez-matias Matu thanks for taking care of this extra backup layer as discussed 🚀 LGTM so I'll proceed to approve it and merge it 💪🏼

**Pull request merged**
